include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ✅ أساسيات النظافة
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    unnecessary_null_checks: true
    prefer_final_fields: true
    prefer_final_locals: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true

    # 🚫 ممنوع الكود المعتمد على الطبقات الخطأ (Clean Architecture)
    implementation_imports: true # يمنع استدعاء كود داخلي مش مخصص للاستدعاء
    depend_on_referenced_packages: true
    directives_ordering: true

    # ⚠️ قواعد زيادة للجودة
    require_trailing_commas: true
    unnecessary_await_in_return: true
    avoid_types_on_closure_parameters: true
    type_annotate_public_apis: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"

  errors:
    missing_required_param: error
    missing_return: error
    dead_code: error
    implementation_imports: error
    depend_on_referenced_packages: error
    unnecessary_import: error